# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qcut.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qcut.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nqcut.proto\x12\x04qcut\"\xab\x01\n\x11\x43utCircuitRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ircuit_qasm\x18\x02 \x01(\t\x12\x15\n\rexport_format\x18\x03 \x01(\t\x12\x10\n\x08gate_cut\x18\x04 \x01(\x08\x12\x16\n\x0eqpu_max_qubits\x18\x05 \x01(\x05\x12\x1b\n\x13\x64\x65pth_threshold_qpu\x18\x06 \x01(\x05\x12\x12\n\nobservable\x18\x07 \x01(\t\"\xaf\x01\n\x12\x43utCircuitResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\x12\x15\n\rmanifest_json\x18\x04 \x01(\t\x12\x16\n\x0e\x66ragments_json\x18\x05 \x01(\t\x12\x16\n\x0epartition_json\x18\x06 \x01(\t\x12%\n\x0bsubcircuits\x18\x07 \x03(\x0b\x32\x10.qcut.Subcircuit\"B\n\nSubcircuit\x12\x13\n\x0b\x66ragment_id\x18\x01 \x01(\t\x12\x0c\n\x04qasm\x18\x02 \x01(\t\x12\x11\n\tmeta_json\x18\x03 \x01(\t2N\n\x0bQCutService\x12?\n\nCutCircuit\x12\x17.qcut.CutCircuitRequest\x1a\x18.qcut.CutCircuitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qcut_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUTCIRCUITREQUEST']._serialized_start=21
  _globals['_CUTCIRCUITREQUEST']._serialized_end=192
  _globals['_CUTCIRCUITRESPONSE']._serialized_start=195
  _globals['_CUTCIRCUITRESPONSE']._serialized_end=370
  _globals['_SUBCIRCUIT']._serialized_start=372
  _globals['_SUBCIRCUIT']._serialized_end=438
  _globals['_QCUTSERVICE']._serialized_start=440
  _globals['_QCUTSERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
